### ISSUE TITLE
Error installing package

### ISSUE THREAD

**Issue by danmalter** [lbenz730/ncaahoopR#101]
> devtools::install_github("lbenz730/ncaahoopR")
Downloading GitHub repo lbenz730/ncaahoopR@HEAD
Error in if (is.na(res)) { : argument is of length zero

I had cleaned my R version and the package is now not installing. I believe it to be due to one of the recent file changes.

**Comment by lbenz730** [comment]
Just pushed a fix. Give it a try now

**Comment by danmalter** [comment]
It works now, thank you.
