### ISSUE TITLE
Game Flow and Win Probability Charts Not working

### ISSUE THREAD

**Issue by anwolfe14** [lbenz730/ncaahoopR#102]
I keep on getting the following error when trying to use game flow and win probability charts

Scraping Data for Game: 1 of 1

Error: parse error: trailing garbage
          eather.com/?partner=espn_gc"},"medialst":{"vids":[{"ad":{"sp
                     (right here) ------^

**Comment by lbenz730** [comment]
Fixed in most recent commit
