### ISSUE TITLE
get_pbp_game error

### ISSUE THREAD

**Issue by jrbarber37** [lbenz730/ncaahoopR#103]
I am getting the following error using this code:  pbp <- get_pbp_game ("401522202")

parse error: trailing garbage
          eather.com/?partner=espn_gc"},"medialst":{"vids":[{"ad":{"sp
                     (right here) ------^

**Comment by lbenz730** [comment]
I think this is related to #102 which is now fixed in latest version.

**Comment by jrbarber37** [comment]
Thank you. 😊
