### ISSUE TITLE
ERROR: missing value where TRUE/FALSE needed in assist_net

### ISSUE THREAD

**Issue by jrbarber37** [lbenz730/ncaahoopR#104]
Full Season assist_net works

output$AssistPlot <- renderPlot(
          assist_net(team = "UConn", node_col = "blue", season = "2022-23"),
           width = 1000,
           height = 500,
           outputArgs = list())

But individual games get -  ERROR: missing value where TRUE/FALSE needed

output$AssistPlot <- renderPlot(
          assist_net(team = "UConn", node_col = "blue", season = 401522202), 
           width = 1000,
           height = 500,
           outputArgs = list())
        }

Thanks

**Comment by lbenz730** [comment]
Should now be fixed in latest commit.

**Comment by jrbarber37** [comment]
Thanks!

**Comment by jrbarber37** [comment]
This is all working great!
