### ISSUE TITLE
assist_net not getting every Assist

### ISSUE THREAD

**Issue by jrbarber37** [lbenz730/ncaahoopR#105]
The assist_net function appears to be missing assists.  As an example, for the championship (gameId=401522202), UConn had 13 assists, but only 4 assists were shown in the Assist Net.

Another example, for gameId= 401522201, UConn had 19 assists, but only 5 assists were shown in the Assist Net. 

In the example on the website (gameId= 401522201, Oklahoma - Kansas, January 23, 2019), Assist Net correctly captures Oklahoma's 14 assists.

I have the most recent version of ncaahoopR - devtools::install_github("lbenz730/ncaahoopR")

**Comment by lbenz730** [comment]
Thanks for alerting me. May be a few days before i can look into it...

**Comment by jrbarber37** [comment]
Thank you for your response.  Please let me know if you need any more
information.

John

**Comment by jrbarber37** [comment]
assist_net appears to not get all assists only for the 2022-23 season.  Also, the following code: assist_net(team = "Yale", node_col = "royalblue4", season = "2022-23") gets the following error: Play-by-Play Data Not Available for Assist Network
assist_net(team = "Yale", node_col = "royalblue4", season = "2021-22") works as expected.

**Comment by jrbarber37** [comment]
This is all working great for me now.  Thanks!

John Barber
