### ISSUE TITLE
get_pbp_data argument length zero

### ISSUE THREAD

**Issue by silfornia** [lbenz730/ncaahoopR#106]
Getting the following pbp scrape error

code
<img width="307" alt="image" src="https://github.com/lbenz730/ncaahoopR/assets/32369650/f305f6db-56b8-464d-b8db-86d7e0ada162">
first 28 games run ok then
<img width="429" alt="image" src="https://github.com/lbenz730/ncaahoopR/assets/32369650/d581f4f6-161c-4315-937d-cbdd21a63202">

Thanks!
-Mike

**Comment by lbenz730** [comment]
Thanks for alerting me. Will be getting down into the weeds in the next week or 2 in advance of 2023-24 season. Will keep you posted when this gets resolved.

--Luke

**Comment by lbenz730** [comment]
Related to this game (https://www.espn.com/mens-college-basketball/playbyplay/_/gameId/401489662)

Will spend time later this week seeing if this issue is something fixable. In any case, `get_pbp_game` should skip games that throw errors like this not stop the entire run of games.

**Comment by silfornia** [comment]
Hi Luke,

Just tried pulling data for 11/17 of this year and am seeing the same error so I think it's relatively common.

<img width="670" alt="image" src="https://github.com/lbenz730/ncaahoopR/assets/32369650/062725d8-a87a-4e8c-bffe-850f90eea79c">
<img width="434" alt="image" src="https://github.com/lbenz730/ncaahoopR/assets/32369650/e79c5660-c91e-49fd-89cc-f6cce26e6b23">

-Mike

**Comment by lbenz730** [comment]
Thanks for reminder. Will get around to fixing it this week

**Comment by lbenz730** [comment]
This is now also fixed in the latest commit
