### ISSUE TITLE
Error when getting schedules

### ISSUE THREAD

**Issue by letta-9** [lbenz730/ncaahoopR#107]
Looking for a little help with an error message. Other functions are working fine but I seem to be having difficulties with get_schedule and get_master_schedule. Any help is appreciated. Thanks.

![image](https://github.com/lbenz730/ncaahoopR/assets/102425378/8b0bdd7b-ed17-4d3f-a60b-40933afbe465)

**Comment by lbenz730** [comment]
Thanks for noting. Looking into it this week

**Comment by lbenz730** [comment]
Updated in latest push
