### ISSUE TITLE
get_master_schedule() returning wrong game IDS

### ISSUE THREAD

**Issue by bmargio** [lbenz730/ncaahoopR#109]
games are getting assigned the wrong ESPN game IDs

**Comment by lbenz730** [comment]
Is this w/ the latest version of the package? It could be they are getting messed up while some games are ongoing.

**Comment by lbenz730** [comment]
Works for previous dates. Looking now into issues on current date

**Comment by lbenz730** [comment]
Ok I think this should be resolved in the latest committ
