### ISSUE TITLE
object 'wp_hoops' not found

### ISSUE THREAD

**Issue by euroleaguedataguy** [lbenz730/ncaahoopR#11]
Hi there, awesome library!
I have encountered this issue when trying to get pbp data:

```
Error in get_pbp_game(game_ids) : object 'wp_hoops' not found
```

**Comment by lbenz730** [comment]
Can you send an example? Are you calling `library(ncaahoopR)` or are you calling `ncaahoopR::get_pbp_game(game_ids)`. The latter does not yet load wp_hoops and will likely yield an error until I get around to fixing it.
