### ISSUE TITLE
get_pbp_game error

### ISSUE THREAD

**Issue by danmalter** [lbenz730/ncaahoopR#111]
On the most recent version of the dev package, I'm getting an error with get_pbp_game().

Example:
get_pbp_game(401574558)

This game details are:
game_id                away                          home               away_score   home_score       date
401574558           Boston College         Vanderbilt        80                   62                       2023-11-29

Scraping Data for Game: 1 of 1
Play-by-Play Data Not Available
NULL
Warning messages:
1: In stringr::str_subset(., "mens-college-basketball/player/_/id") :
  restarting interrupted promise evaluation
2: In stringr::str_subset(., "mens-college-basketball/player/_/id") :
  internal error -3 in R_decompress1

**Comment by lbenz730** [comment]
I'm unable to reproduce this. I am guessing you need to restart your session and try again.
