### ISSUE TITLE
get_pbp_game() not working for certain games

### ISSUE THREAD

**Issue by danmalter** [lbenz730/ncaahoopR#113]
It seems like there might be an error in get_pbp_game(), but I can't quite figure out where. In the below example, get_pbp("Duke", "2023-24") scrapes all 12 of Duke's games so far, but get_pbp_game only works for the below 8 games. For example, they have a game against Baylor with game ID 401576153, but it's not being picked up by get_pbp_game() even though data exists on ESPN.
https://www.espn.com/mens-college-basketball/playbyplay/_/gameId/401576153

Example:
duke <- get_pbp("Duke", "2023-24")

library(dplyr)
duke %>% select(game_id, home, away) %>% unique()

Output:
game_id             home               away
401576147         Duke               Dartmouth
401576150         Duke               Bucknell
401576151          Duke                La Salle
401576152         Duke               So Indiana
401604090        Georgia Tech       Duke
401576153         Duke              Charlotte
401576154         Duke              Hofstra
401574497         Duke              Queens

**Comment by lbenz730** [comment]
Seems it was messing up Neutral site games. Just patched it in latest version.
