### ISSUE TITLE
Score on 1st possession not updated until next play (when there is no jump ball data)

### ISSUE THREAD

**Issue by CBBHooper** [lbenz730/ncaahoopR#117]
See in example 1 how the score doesn't reflect the first bucket

![cbbexample2](https://github.com/lbenz730/ncaahoopR/assets/159098462/47d3c67e-3c45-49be-94fd-eff0c8438db4)

But in example 2 it does

![cbbexample3](https://github.com/lbenz730/ncaahoopR/assets/159098462/f17db19f-f1e8-405a-b73b-2eb2345d5bb5)

Seems that it affects every game without jump-ball data, where there is also a score on the first play

**Comment by lbenz730** [comment]
Thanks for bringing to my attention. I will see if I can get a fix deployed this week.

**Comment by lbenz730** [comment]
This is now fixed in the latest version. Just re-install and let me know if it persists.

**Comment by CBBHooper** [comment]
Thank you! Does not seem to have fixed all instances though. See this example

![cbbexample4](https://github.com/lbenz730/ncaahoopR/assets/159098462/1bca98d7-5ba1-4fe7-8508-0142757d46a4)

**Comment by lbenz730** [comment]
Ah sorry I made a typo. It's now fixed for real.
