### ISSUE TITLE
get_roster

### ISSUE THREAD

**Issue by jrbarber37** [lbenz730/ncaahoopR#118]
I am trying to get the rosters for all the NCAA tournament teams.  I am using the same code as last year (listed below).

StetsonRoster <- get_roster("Stetson", "2023-24")

I am getting the following error.

Error in function (type, msg, asError = TRUE)  : 
  error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version

Thanks.

**Comment by lbenz730** [comment]
I can't reproduce this error. Seems like it's an ssl or server error on your end. If you need rosters you can get them here

https://github.com/lbenz730/ncaahoopR_data

**Comment by jrbarber37** [comment]
Thank you for your response.  I'll check out the rosters.

John Barber
