### ISSUE TITLE
issue with get_pbp and get_pbp_game

### ISSUE THREAD

**Issue by tdp-datsci** [lbenz730/ncaahoopR#119]
I am getting NULL for get_pbp and get_pbp_game with version 1.8.5.6. The message 

Scraping Data for Game: 1 of 1
Play-by-Play Data Not Available

The other functions that appear to be affected:

wp_chart_new
game_flow
game_excitement_index
average_win_prob
average_score_diff

**Comment by lbenz730** [comment]
Fixed in latest commit
