### ISSUE TITLE
Summer HTML mixup

### ISSUE THREAD

**Issue by lbenz730** [lbenz730/ncaahoopR#12]
Fix functions when ESPN does summer archiving. Add historical data for past years as well.

**Comment by snestler** [comment]
When will it be possible to pull data from last year?  I'd like to get familiar with the package before the season starts this year.  Thank you.

**Comment by lbenz730** [comment]
This bug should be fixed I think. If you want past data, check out the pbp_data or test_pbp_data folder at https://github.com/lbenz730/Senior-Thesis. Or choose an ESPN game_id and scrape data for that game. 

I don't have functionality to pull past season's schedules to extract game_ids at large scale but hoping to have those out soon.
