### ISSUE TITLE
Roster Errors

### ISSUE THREAD

**Issue by vigslayer** [lbenz730/ncaahoopR#122]
Two teams are popping roster errors for 2024-25: Le Moyne and Houston Christian.

![image](https://github.com/user-attachments/assets/400e7526-bd47-43a4-b29f-32bb7e74f80d)
![image](https://github.com/user-attachments/assets/baa26116-3811-4518-b33c-18da1cff78ad)

**Comment by lbenz730** [comment]
Thanks. I will need to go through more carefully when I have time to correct all the new team names, IDs, conferences, add in new teams etc...

**Comment by tdp-datsci** [comment]
Luke, if you are interested I have a spreadsheet that has all of the conference changes and new teams for the 2024-25 season. The only items that I do not have is the ESPN abbreviation for a couple of teams (Mercyhurst and West Georgia). Just let me know.

**Comment by lbenz730** [comment]
would be very helpful!

**Comment by tdp-datsci** [comment]
[conferences.xlsx](https://github.com/user-attachments/files/17672027/conferences.xlsx)

The sheet is attached. Houston Christian is now Houston Baptist. The following teams do not work: Mercyhurst, West Georgia and Le Moyne. There may be others. 

If there are any errors or questions, please let me know.

**Comment by lbenz730** [comment]
thank you all for your patience. This should now be fixed in the latest pull, including the addition of new teams/conferences for the 2024-25 season.
