### ISSUE TITLE
Shot location data not available for 2024-25 NCAAB games

### ISSUE THREAD

**Issue by aqsmith08** [lbenz730/ncaahoopR#123]
The Cincinnati vs AR-Pine Bluff [game](https://www.espn.com/mens-college-basketball/boxscore/_/gameId/401715627) was played on November 4, but I don't get shot location data when I run the following:

```
> library(ncaahoopR)
> df <- get_shot_locs(game_id = 401715627)
Getting Shots for Game 1 of 1
No shot location data available for this game.
```

Is there typically a delay? How can we get this stood up for the current season? Thanks!

**Comment by lbenz730** [comment]
Most games don't have shot locations. 

https://www.espn.com/mens-college-basketball/game/_/gameId/401715627/ar-pine-bluff-cincinnati

As you can see no location data available here

**Comment by aqsmith08** [comment]
Bah, that's a bummer. I just assumed that all NCAAB games would have shot locations these days. Ok, thanks!
