### ISSUE TITLE
get_pbp_game not working

### ISSUE THREAD

**Issue by quinnjohnson303** [lbenz730/ncaahoopR#13]
When running get_pbp_game(gameid), it begins scraping and then gets cut off with an error that reads "Error in if (length(tmp) < ncol(tmp[[1]]) | length(tmp) == 0) { : 
  argument is of length zero".

**Comment by quinnjohnson303** [comment]
After reviewing the code, this error comes from line 42 in ncaa_pbp_scraper.R.

**Comment by quinnjohnson303** [comment]
After further investigation, in almost every instance where ____[[#]] is in the code there is an error. `(length(tmp) < ncol(tmp[[1]]) | length(tmp) == 0) #Just happens to be the first case.`

**Comment by lbenz730** [comment]
Thanks ESPN summer HTML change. Will have it fixed by end of week.

**Comment by lbenz730** [comment]
The `get_pbp()` and `get_pbp_game()` functions should be fixed. I'll have to patch up some other functions but I think this is now working in the meantime.
