### ISSUE TITLE
Single shot charts/shot heatmaps for series of opponents

### ISSUE THREAD

**Issue by morrisLuke** [lbenz730/ncaahoopR#18]
Similar to what `team_shot_chart()` does for mapping a team's offense, it would be great if you could input a vector of game ids for a particular team and get an aggregated shot chart or shot heatmap of their opponents' shooting. 

I've attempted using `team != "Kansas"` within `team_shot_chart()` to execute something like this with no luck.

**Comment by lbenz730** [comment]
Fixed in version 1.4.7
