### ISSUE TITLE
Is there any way to get substitution information in the play by play?

### ISSUE THREAD

**Issue by GaryLeeONE** [lbenz730/ncaahoopR#20]
It seems like there's no substitution info on ESPN. I found that the play by play from NCAA.org contains this information, for example [here](https://stats.ncaa.org/game/play_by_play/4866920). I wonder if you could add this feature. Thank you so much

**Comment by lbenz730** [comment]
See the `bigballR` package which scrapes NCAA basketball stats from NCAA.org. I think the NCAA data is a little messier but this should hopefully help you get some stuff you may be interested in. 

https://github.com/jflancer/bigballR
