### ISSUE TITLE
Parsing error on Campbell game

### ISSUE THREAD

**Issue by akeaswaran** [lbenz730/ncaahoopR#23]
Great library, man -- thanks for putting this all together and enabling better analysis of CBB!

Currently trying to iterate through a set of teams from the library's team dictionary and pull in some play-by-play data, and I'm running into an issue with `get_pbp('Campbell')`. Looks like on Campbell's 21st game, the PBP parser bails out with the error: `Error in if (length(tmp) < ncol(tmp[[1]]) | length(tmp) == 0) { : 
  argument is of length zero`.

Working backward through the stacktrace, I'm fairly sure [this line](https://github.com/lbenz730/ncaahoopR/blob/master/R/ncaa_pbp_scraper.R#L40) is the culprit. Looks like the URL for the game in question (https://www.espn.com/mens-college-basketball/game?gameId=401171028) just redirects to the NCAA scoreboard, rather than displaying any game data.

Let me know if you need any other information to debug this!

Edit: Looks like Coastal Carolina has the same issue in its second game, based on its [schedule](https://www.espn.com/mens-college-basketball/team/schedule/_/id/324). Hampden-Sydney is not a D1 school (from what I can tell), so it doesn't have a ESPN game summary associated with games against it.

**Comment by lbenz730** [comment]
Fixed in latest commit, thanks!
