### ISSUE TITLE
Reduce scraping requests with memoise

### ISSUE THREAD

**Issue by jimmyg3g** [lbenz730/ncaahoopR#28]
Decrease the number of scraping requests and speed things up with `memoise` ([https://github.com/r-lib/memoise](url)). Memoise can cache function results (locally or in the cloud), useful for functions called multiple times with the same input. For example, functions relying on `get_pbp_game()` will benefit from caching `get_pbp_game()` results. 

Checkout `googleAnalyticsR` ([http://code.markedmondson.me/googleAnalyticsR/](url)) to see `memoise` in action.

**Comment by lbenz730** [comment]
Thanks this is a neat idea. I will look into this and think about caching for speeding up work flows.

**Comment by lbenz730** [comment]
Future releases of ncaahoopR may utilize 
1) option to pass a pre-scraped PBP dataset to plotting/summary functions
2) option to read file directly from the [ncaahoopR_data](https://github.com/lbenz730/ncaahoopR_data) repository (if available).
