### ISSUE TITLE
shot_team NA in middle of game

### ISSUE THREAD

**Issue by naymikm** [lbenz730/ncaahoopR#29]
I'm guessing this is due to player name discrepancies. Could these be assigned via the possession_before column? 

`df$shot_team = ifelse(is.na(df$shot_team) & !is.na(df$shot_outcome), df$possession_before, df$shot_team)`

**Comment by lbenz730** [comment]
Yes thanks this is a good suggestion. I will add in a future release.

**Comment by lbenz730** [comment]
Fixed w/ latest push.
