### ISSUE TITLE
get_master_schedule doesn't work for dates in advance 

### ISSUE THREAD

**Issue by meysubb** [lbenz730/ncaahoopR#3]
Hey @lbenz730 

Looks like the `get_master_schedule` works fine for dates in the past. But struggles with future dates. After, playing with the source code a bit, it seems like the issue is in these lines 

```{R}
scores <- as.numeric(gsub("[^0-9]", "", gsub("\\(.*\\)", "", unlist(strsplit(completed$result, ",")))))
winning_scores <- scores[seq(1, length(scores) - 1, 2)]
losing_scores <- scores[seq(2, length(scores), 2)]
```

The length of scores (for future dates) is 1 and that is throwing an error when trying to find winning scores and losing scores. On first thought maybe an if...else statement could clarify that issue. I should have submitted a PR but was too lazy to fork the code -___-. 

I could also be using the function outside of the intended scope.

**Comment by lbenz730** [comment]
Problem should be fixed now.
