### ISSUE TITLE
Error when scaping data (get_pbp)

### ISSUE THREAD

**Issue by ThiagoMCarneiro** [lbenz730/ncaahoopR#31]
I'm trying to get data from UVA (Virginia Cavaliers) for 2019-20 and I see this Error:

> get_pbp("UVA","2019-20")

Getting Game IDs: UVA
Scraping Data for Game: 1 of 13
Error in if (extra_parse & (pbp$date[1] >= "2007-11-01")) { : 
  missing value where TRUE/FALSE needed

A similar message appears for all teams and seasons when I try to execute the code.

I'm sorry for the incovenience, but what am I doing wrong?

**Comment by lbenz730** [comment]
Hmmm I am unable to replicate this issue. Can you try reinstalling package?

**Comment by ThiagoMCarneiro** [comment]
I've tried to reinstall it - both using Ubuntu 16.04 LTS and Windows 10. R versions: 3.61 (Ubuntu), 3.53 (Windows).

Same problem.

I'm sorry for taking your time, but I think you'd like to receive such reports, it could be happening to more random people and computers.

________________________________
De: Luke Benz <notifications@github.com>
Enviado: terça-feira, 7 de janeiro de 2020 22:12
Para: lbenz730/ncaahoopR <ncaahoopR@noreply.github.com>
Cc: ThiagoMCarneiro <thiagomotacarneiro@hotmail.com>; Author <author@noreply.github.com>
Assunto: Re: [lbenz730/ncaahoopR] Error when scaping data (get_pbp) (#31)


Hmmm I am unable to replicate this issue. Can you try reinstalling package?

**Comment by ThiagoMCarneiro** [comment]
I think it's something related to the function "get_date". If the conditional is complaining about a NA, it means pbp_date isn't working properly when receiving get_date(games_ids[g]).

From which package does "get_date" come from? I think I can fix it if I reinstall this package.

Thank you very much for you attention and I'm sorry for bothering you.


Enviado do Outlook<http://aka.ms/weboutlook>

________________________________
De: Luke Benz <notifications@github.com>
Enviado: terça-feira, 7 de janeiro de 2020 22:12
Para: lbenz730/ncaahoopR <ncaahoopR@noreply.github.com>
Cc: ThiagoMCarneiro <thiagomotacarneiro@hotmail.com>; Author <author@noreply.github.com>
Assunto: Re: [lbenz730/ncaahoopR] Error when scaping data (get_pbp) (#31)


Hmmm I am unable to replicate this issue. Can you try reinstalling package?

**Comment by lbenz730** [comment]
Can you try this command and show me the output.

```get_schedule("Duke")```

The `get_date()` function is internal to the package (a helper function) so it should be installed along w/ everything else.

**Comment by ThiagoMCarneiro** [comment]
Thank you very much for your patience!

I sent you a printscreen. Any hint?


Enviado do Outlook<http://aka.ms/weboutlook>

________________________________
De: Luke Benz <notifications@github.com>
Enviado: quarta-feira, 8 de janeiro de 2020 09:44
Para: lbenz730/ncaahoopR <ncaahoopR@noreply.github.com>
Cc: ThiagoMCarneiro <thiagomotacarneiro@hotmail.com>; Author <author@noreply.github.com>
Assunto: Re: [lbenz730/ncaahoopR] Error when scaping data (get_pbp) (#31)


Can you try this command and show me the output.

get_schedule("Duke")

The get_date() function is internal to the package (a helper function) so it should be installed along w/ everything else.

**Comment by lbenz730** [comment]
I don't see the print screen. Can you post a screen shot here?

**Comment by ThiagoMCarneiro** [comment]
Did it work now? Thank you for your support!


Enviado do Outlook<http://aka.ms/weboutlook>

________________________________
De: Luke Benz <notifications@github.com>
Enviado: segunda-feira, 13 de janeiro de 2020 13:07
Para: lbenz730/ncaahoopR <ncaahoopR@noreply.github.com>
Cc: ThiagoMCarneiro <thiagomotacarneiro@hotmail.com>; Author <author@noreply.github.com>
Assunto: Re: [lbenz730/ncaahoopR] Error when scaping data (get_pbp) (#31)


I don't see the print screen. Can you post a screen shot here?

**Comment by lbenz730** [comment]
I'm not sure how you sending it? I don't see anything here or via email?

**Comment by ThiagoMCarneiro** [comment]
![0001](https://user-images.githubusercontent.com/59610106/72518683-9e173f80-3834-11ea-8ebd-10a7fbac7d10.png)
![0002](https://user-images.githubusercontent.com/59610106/72518684-9e173f80-3834-11ea-89a2-62d9cdecae14.png)

**Comment by lbenz730** [comment]
Yeah I'm even more puzzled now because the get_date function works fine in the get_schedule function. I'm sorry to say I'm not sure what your issue could be. Does the get_pbp seem to be the only function not working for you?

**Comment by hutchngo** [comment]
@lbenz730 came across this issue when attempting to get_pbp data for Army

Getting Game IDs: Army
Error in `$<-.data.frame`(`*tmp*`, "game_id", value = c("401169778", "401172236",  : 
  replacement has 30 rows, data has 29

**Comment by lbenz730** [comment]
@hutchngo this was fixed in v1.5.2 . Please reinstall and this issue shouldn’t persist.

**Comment by hutchngo** [comment]
Thanks @lbenz730!
