### ISSUE TITLE
get_master_schedule - cancelled games returns error (because of invalid scores)

### ISSUE THREAD

**Issue by meysubb** [lbenz730/ncaahoopR#4]
Hey @lbenz730.

SEC charts just bounced back on me, and I realized today that get_master_schedule throws an error for canceled/postponed games. The reason for this is right here.

When you filter out in completed, the scores are filled with NA. So this `if` statement with the `seq` throws an error. 

The `score` variable is just a vector of length 1 with NA in it. 

```R
 if(length(scores) > 0) {
     winning_scores <- scores[seq(1, length(scores) - 1, 2)]
     losing_scores <- scores[seq(2, length(scores), 2)]
     
     index <- sapply(completed$away_anchor, function(y) { y %in% winners })
     completed$home_score[index] <- losing_scores[index]
     completed$home_score[!index] <- winning_scores[!index]
     completed$away_score[!index] <- losing_scores[!index]
     completed$away_score[index] <- winning_scores[index]
 }
```

**Comment by lbenz730** [comment]
Thanks I added extra filtering to remove postponed games first. Should be fixed now.
