### ISSUE TITLE
get_game_ids : Historical year

### ISSUE THREAD

**Issue by dylorr** [lbenz730/ncaahoopR#42]
I'll randomly get an error with these types of queries (pulling historical game ids) - the most recent to pop up is:

ex: get_game_ids(team = 'Virginia Tech', season ='2017-18')

`Error in if (reg_flag > 1) { : argument is of length zero`

Safer to just download archives? Deploying a Shiny app that allows for querying of shot location data by team, year and player and want to be able to support historical querying while also keeping app size down, but seems that historical pulling has its drawbacks w/r to ESPN changing things on their backend and causing random errors to pop up 🤷‍♂️

**Comment by lbenz730** [comment]
Hi thanks for bringing to my attention. Issue is now fixed. Feel free to use persisted data [here](https://github.com/lbenz730/ncaahoopR_data) if you'd like.

**Comment by dylorr** [comment]
Thanks so much! Would you suggest any way of getting around shiny apps item limit for apps? Using multiple years of the persisted data puts me well over the 10k item limit and wondering if you encountered this/how you managed you way around this

**Comment by lbenz730** [comment]
I'd suggest putting the data into some kind of SQL database if the files are an issue 
https://shiny.rstudio.com/articles/persistent-data-storage.html

A less good option but still one that should work if you're unfamiliar w/ SQL is to just read files from that GitHub repo like `https://raw.githubusercontent.com/lbenz730/ncaahoopR_data/master/2002-03/pbp_logs/2003-03-20/234000001.csv`

**Comment by dylorr** [comment]
an s3 bucket did the trick, thanks for the tip!

**Comment by akaushik1998** [comment]
Hey Luke, I'm having this same problem. I just reinstalled the package and having the same issue on two diff computers/ versions of R. 

`get_game_ids(team = 'Virginia Tech', season ='2017-18')`
`Error in if (reg_flag > 1) { : argument is of length zero`
