### ISSUE TITLE
get_boxscore for teams with hyphens 

### ISSUE THREAD

**Issue by dylorr** [lbenz730/ncaahoopR#43]
Seems to be an issue with pulling box scores for a matchup where there is a team name containing a hyphen. It will return a list with the other team's data missing and with a name of '<unknown>' 

Can be fixed by just changing: 

`	matchup <- unlist(strsplit(pagetext, "-"))[[1]][1]
`

to 

`matchup <- unlist(strsplit(pagetext, " - "))[[1]][1]
`

so it splits on the correct hyphen and not on the potential team name hyphen.

**Comment by lbenz730** [comment]
Fixed via #44
