### ISSUE TITLE
Error installing package with R v4.0.2

### ISSUE THREAD

**Issue by akaushik1998** [lbenz730/ncaahoopR#45]
Hi,

I had a couple errors trying to install ncaahoopR , I'm wondering if they're problems on my end or with the package. 

If I try to install the package using 'install.packages' I get the following error: 
Warning in install.packages :
  package ‘ncaahoopR’ is not available (for R version 4.0.2)

If I try to install the package using the github repo + devtools I get this error: 

Homebrew 2.1.4
Homebrew/homebrew-core (git revision 3d75; last commit 2019-06-03)
Using PKG_CFLAGS=-I/usr/local/opt/openssl@1.1/include -I/usr/local/opt/openssl/include
--------------------------- [ANTICONF] --------------------------------
Configuration failed because openssl was not found. Try installing:
 * deb: libssl-dev (Debian, Ubuntu, etc)
 * rpm: openssl-devel (Fedora, CentOS, RHEL)
 * csw: libssl_dev (Solaris)
 * brew: openssl@1.1 (Mac OSX)
If openssl is already installed, check that 'pkg-config' is in your
PATH and PKG_CONFIG_PATH contains a openssl.pc file. If pkg-config
is unavailable you can set INCLUDE_DIR and LIB_DIR manually via:
R CMD INSTALL --configure-vars='INCLUDE_DIR=... LIB_DIR=...'
-------------------------- [ERROR MESSAGE] ---------------------------
tools/version.c:1:10: fatal error: 'openssl/opensslv.h' file not found
#include <openssl/opensslv.h>
         ^~~~~~~~~~~~~~~~~~~~
1 error generated.
--------------------------------------------------------------------
ERROR: configuration failed for package ‘openssl’
* removing ‘/Library/Frameworks/R.framework/Versions/4.0/Resources/library/openssl’
Error: Failed to install 'ncaahoopR' from GitHub:
  (converted from warning) installation of package ‘openssl’ had non-zero exit status

Thanks for any help,
Aditya

**Comment by lbenz730** [comment]
First issue makes sense as package is not yet on CRAN. Second issue is from running `devtools::install_github("lbenz730/ncaahoopR")` ? Admittedly this package was developed under R 3.6.2 so it could be an issue w/ the package but hard for me to say. Can you provide any more information about the environment you are trying to install this into?

**Comment by lbenz730** [comment]
FWIW I tried installing package in R 4.0.0 could environment and seemed to install fine. Seems like it could be a user issue.

**Comment by akaushik1998** [comment]
Yeah thanks for the response, &  for followup I managed to fix it. I think the openssl package was uninstalled for some reason when I updated the macbook to Catalina. With some googling though I was able to find a solution.
