### ISSUE TITLE
Getting rosters from previous years

### ISSUE THREAD

**Issue by ehrenj1** [lbenz730/ncaahoopR#49]
Hi Luke,

It looks like ESPN has updated all the rosters for the upcoming season, but now when I try to get the rosters from last year I am getting an error. The link is working to get to the .json data (https://barttorvik.com/2020_rosters.json), but it looks like it it is breaking at the fromJSON function.  Is this an internal issue on my end, or something new on Bart's site?
  
![image](https://user-images.githubusercontent.com/57914740/97946651-136ae700-1d59-11eb-9c74-bfda4c16abb6.png)

Thanks,
Justin

**Comment by lbenz730** [comment]
Hi Justin, I'm not having any issues on my end. Can you give me an example of a call to get_roster function that was giving you trouble, and hope we can get you sorted out. Thanks, Luke

**Comment by lbenz730** [comment]
Fixed in latest commit
