### ISSUE TITLE
dict ESPN_PBP name fixes

### ISSUE THREAD

**Issue by naymikm** [lbenz730/ncaahoopR#51]
I noticed some of the PBP names are off in the 'dict' dataframe. I have been scraping boxscores for the 2016-17 and 2017-18 season but it looks like the name in the boxscore list is the same as the name in pbp data (I only spot checked a few of these in pbp but the boxscores for sure use this name). These are the changes that I have reconciled:

dict$ESPN_PBP[dict$ESPN_PBP == 'Arkansas State'] = 'Arkansas St'
dict$ESPN_PBP[dict$ESPN_PBP == 'Fort Wayne'] = 'Purdue Fort Wayne'
dict$ESPN_PBP[dict$ESPN_PBP == 'Georgia State'] = 'Georgia St'
dict$ESPN_PBP[dict$ESPN_PBP == 'Little Rock'] = 'Arkansas-Little Rock'
dict$ESPN_PBP[dict$ESPN_PBP == 'Louisiana'] = 'Lafayette'
dict$ESPN_PBP[dict$ESPN_PBP == 'Loyola-Chicago'] = 'Loyola Chicago'
dict$ESPN_PBP[dict$ESPN_PBP == 'McNeese'] = 'Mcneese St'
dict$ESPN_PBP[dict$ESPN_PBP == "Mt. St. Mary's"] = "Mt. St. Mary'S"
dict$ESPN_PBP[dict$ESPN_PBP == "San JosÃ© St"] = "San José State"
dict$ESPN_PBP[dict$ESPN_PBP == 'Southeast Missouri'] = 'Southeast Missouri State'
dict$ESPN_PBP[dict$ESPN_PBP == 'Seattle'] = 'Seattle U'
dict$ESPN_PBP[dict$ESPN_PBP == 'SIU-Edwardsville'] = 'SIU Edwardsville'
dict$ESPN_PBP[dict$ESPN_PBP == 'UL Monroe'] = 'Ul Monroe'
dict$ESPN_PBP[dict$ESPN_PBP == 'UMKC'] = 'UM Kansas City'

**Comment by lbenz730** [comment]
Thanks I'll look into this.

**Comment by lbenz730** [comment]
Fixed these in `dict`. Let me know if you find any others.
