### ISSUE TITLE
New teams to D1 - create_ids_df

### ISSUE THREAD

**Issue by ehrenj1** [lbenz730/ncaahoopR#52]
Four new teams have moved to D1 this year, and it doesn't look like your create_ids_df function has been updated to reflect this.  To start, when you initiate the "ids" data frame, it should have 357 observations instead of 353.  Then, it looks like there is a bug when you fill in the rest of the teams at the end of the function.  Some of the teams were mismatched as seen in the snip below:
![image](https://user-images.githubusercontent.com/57914740/99881279-c5723200-2be6-11eb-80bd-59ada49bd947.png)

**Comment by lbenz730** [comment]
Thanks for bringing this to my attention I'll fix it this week

**Comment by lbenz730** [comment]
Fixed in latest commit thanks
