### ISSUE TITLE
GET_PBP Parse Error

### ISSUE THREAD

**Issue by silfornia** [lbenz730/ncaahoopR#53]
Pretty sure I am up to date on all packages, but am new to using R/ncaahoopR.

Getting this error when pulling full season PBP:

![image](https://user-images.githubusercontent.com/32369650/100485494-4c834680-30ce-11eb-8fe5-acc2a3890116.png)

Thanks for all that you do Luke!
-Mike

**Comment by lbenz730** [comment]
Just pushed a fix. Re-install and should be fixed. Thanks!

--LB
