### ISSUE TITLE
`free_throw` column incorrect

### ISSUE THREAD

**Issue by JackLich10** [lbenz730/ncaahoopR#54]
The free_throw column appears to be NA or FALSE only (it never shows up as being TRUE and all of the shot information of the free throw attempt in shot_team, shot_outcome is NA as well). For example, when running for the Duke vs. Mich St. game: `ncaahoopR::get_pbp_game("401260005")`, this issue occurs.

**Comment by lbenz730** [comment]
Thanks I will take a look.

**Comment by lbenz730** [comment]
Fixed this in latest commit.

**Comment by JackLich10** [comment]
The `shot_team` column is still blank for free throws. I think adding `pbp$shot_team[(made_shots | missed_shots) & tolower(pbp$shooter) %in% tolower(home_roster)] <- pbp$home[1]` and `pbp$shot_team[(made_shots | missed_shots) & tolower(pbp$shooter) %in% tolower(away_roster)] <- pbp$away[1]` to the end of the `if (extra_parse == T)` statement should fix this. I think this problem is occurring this year because ESPN is no longer marking the shot location of free throws as right underneath the basket - (25, 87.94222222222221) or (25, 4.177777777777778).
