### ISSUE TITLE
`shot_team` for free throws missing

### ISSUE THREAD

**Issue by JackLich10** [lbenz730/ncaahoopR#55]
Not sure if you saw my comment under the recently closed issue [#54](https://github.com/lbenz730/ncaahoopR/issues/54), so I will open this new issue here: The shot_team column is still blank for free throws. I think adding pbp$shot_team[(made_shots | missed_shots) & tolower(pbp$shooter) %in% tolower(home_roster)] <- pbp$home[1] and pbp$shot_team[(made_shots | missed_shots) & tolower(pbp$shooter) %in% tolower(away_roster)] <- pbp$away[1] to the end of the if (extra_parse == T) statement should fix this. I think these free throw related problems are occurring this year because ESPN is no longer marking the shot location of free throws as right underneath the basket - (25, 87.94222222222221) or (25, 4.177777777777778). Thanks for your hard work maintaining the package!

**Comment by lbenz730** [comment]
Ok nice catch. I fixed this too. Appreciate the help.
