### ISSUE TITLE
PBP Scrape Issue with Games on 1/2/21

### ISSUE THREAD

**Issue by silfornia** [lbenz730/ncaahoopR#57]
Using the commands below I'm trying to get PBP data for 1/2/21. Error causes no data to be saved.

Other recent dates seem to be fine.

Thanks
-Mike

![image](https://user-images.githubusercontent.com/32369650/103704662-a4d42080-4f77-11eb-812a-ba6f92b98aa2.png)

![image](https://user-images.githubusercontent.com/32369650/103704624-9554d780-4f77-11eb-8a52-b770c706bd28.png)

**Comment by silfornia** [comment]
Starting to see this arena error more. Here's an example from 1/5/21. Included the install command just to show I am up to date.

Do you have a tip jar btw?

Thanks
-Mike

![image](https://user-images.githubusercontent.com/32369650/103954359-0b8d4180-5112-11eb-9ff8-094102fcad78.png)

**Comment by lbenz730** [comment]
Thanks for bringing to my attention. I'll take a look and see if we can't it resolved quickly. No obligation whatsoever but I'd accept tips via venmo (@lbenz730) or paypal(lsbenz30@yahoo.com).

**Comment by lbenz730** [comment]
Ok should be fixed now upon re-installing package.

**Comment by silfornia** [comment]
Thanks Luke. Just tried installing but 'ggplot2' is deemed as still in use. Not sure if you still have it locked out.

**Comment by lbenz730** [comment]
Try to start a fresh R session for install to work.

**Comment by silfornia** [comment]
Thanks. Working now. Bit of an R rookie =)

**Comment by lbenz730** [comment]
Glad you got it working!
