### ISSUE TITLE
Previous Season Schedules

### ISSUE THREAD

**Issue by fmathews11** [lbenz730/ncaahoopR#59]
Greetings!

First of all, thank you so much for this package.  I've used it a ton through this season.

I've noticed the "get_schedule()" function isn't working properly when you pass a previous season argument.  It does, however, still work flawlessly for the current season.  Am I correct in that the format is "2019-20"?

![image](https://user-images.githubusercontent.com/63658905/110559095-9d64fb00-8111-11eb-997a-3a75f3d0e37a.png)

Thanks!

**Comment by lbenz730** [comment]
Thanks for the tip. You are correct in the usage. Some ties ESPN changes HTML format on their pages. Should hopefully be an easy fix.

**Comment by lbenz730** [comment]
Fixed in latest commit. Please re-install the package and everything should work fine.
