### ISSUE TITLE
get_schedule function error

### ISSUE THREAD

**Issue by jake23brown** [lbenz730/ncaahoopR#62]
Myself and some others are having issues with the get_schedule and get_pbp functions. Everything else is working fine, but something is off with these two. They produce the same error message:

Error in get_schedule("Penn State", "2020-21") : 
  No team schedule available for Penn State / 2020-21. Current ESPN season = "2020-21". If you are trying to find the most recent season (2019-20), please  supply season = "2019-20" argument.

Any help or solution would be appreciated!

**Comment by lbenz730** [comment]
Will do my best to fix this week. Thanks for letting me know

**Comment by lbenz730** [comment]
Fixed. Just re-install and should now work. Let me know if anything else broken. Thanks!

**Comment by jake23brown** [comment]
Thanks!
________________________________
