### ISSUE TITLE
tibble column sizes not compatible before 2020 season

### ISSUE THREAD

**Issue by jaketroch** [lbenz730/ncaahoopR#68]
![image](https://user-images.githubusercontent.com/48990760/150547611-62564139-5fe5-4f80-8421-2e249dffa2e9.png)

**Comment by lbenz730** [comment]
I actually pushed a fix for this yesterday. Try a fresh install and this should be fixed.

**Comment by jaketroch** [comment]
Yeah I'm actually working with zach on something with it. This occurred after a fresh install this morning. I will re-install again and try. Thanks!

**Comment by lbenz730** [comment]
Cool, well let me know if it persists. Here is what i am seeing on my machine for example
![Screen Shot 2022-01-21 at 2 37 26 PM](https://user-images.githubusercontent.com/21962947/150589674-3648f0b2-e273-4078-87e4-4ff5687d5d54.png)
