### ISSUE TITLE
get_game_ids.R returning an empty character string

### ISSUE THREAD

**Issue by davidlparks** [lbenz730/ncaahoopR#69]
The function `get_game_ids()` is returning an empty character string without throwing an error. I believe the issue is on line 25 of get_game_ids.R

The call to `x <- x[grep("club-schedule", x)]` results in an empty string. After looking at the html on ESPN's website, the class name was changed to "Schedule__Group". Running the code with `x <- x[grep("Schedule__Group", x)]` returns a list of game ids. Hope this helps.

**Comment by lbenz730** [comment]
Thanks for alerting me. Seems like making the substitution you mentioned yields only a subset of the game_ids. I will dig into it and hopefully have a fix shortly.

**Comment by lbenz730** [comment]
Ok fixed. Take a pull and let me know if you have any other issues.
