### ISSUE TITLE
Font Error in assist_net function

### ISSUE THREAD

**Issue by j-andrews7** [lbenz730/ncaahoopR#7]
Hey Luke,

Nifty package, quite a fan. Thanks for making it.

I've run into an error when trying to create an assist_network and have it saved as a pdf. I use Jupyter notebook and R 3.4.4. Plotting within the notebook works fine, but the error occurs in R sessions opened from the command line as well. Not a huge deal, but I have been struggling with text getting cut off and wanted to bring it back into frame in Illustrator or something rather than distort the entire image by screwing with image dimensions. 

To replicate:
```R
pdf("tester.pdf")
assist_net("Louisville", 401082663, louisville$primary_color, message = "Assist Network - Louisville v Clemson 02/16/2019")
dev.off()
```

Error (repeated a few dozen times):
```R
Warning message in text.default(x, y, labels = labels, col = label.color, family = label.family, :
“font family 'Arial Black' not found in PostScript font database”
```

Clearly, the Arial Black font is missing, but I'm not sure how to rectify it. I tried mucking about with the extrafont package, but with no luck. Any hints or solutions would be much appreciated. Thanks!

**Comment by lbenz730** [comment]
I don't have a fix for this at the moment without changing the default font, which PDF doesn't seem to like. I will look into it and make the text on plots better at some point. In the meantime, I'd suggest using a Jupyter or RStudio Workflow or switching to `circle_assist_net()`.
