### ISSUE TITLE
Bug: ESPN changed their schedule interface

### ISSUE THREAD

**Issue by evanmiyakawa** [lbenz730/ncaahoopR#71]
Just a heads up, it looks like ESPN changed the entire way the schedule page looks, which probably affects all relevant functions.

**Comment by lbenz730** [comment]
Thanks for the heads up, I actually think I fixed an issue of this sort over the weekend. If you re-install pkg everything should work, but definitely let me know if this is not the case.

**Comment by evanmiyakawa** [comment]
<img width="769" alt="Screen Shot 2022-02-17 at 9 15 49 AM" src="https://user-images.githubusercontent.com/25516384/154499876-4fd252e2-09d7-406e-86e2-f1293c2ad7d9.png">

Just re-installed and got the following results with missing game ids and weird characters in the away teams.

**Comment by lbenz730** [comment]
Ah shoot ok this is different than an issue the other day. Let me fix this and push a fix.

**Comment by lbenz730** [comment]
` get_master_schedule(Sys.Date()-1)
     game_id                 away                     home away_rank home_rank away_score home_score       date
1  401371316              Gonzaga               Pepperdine         1        NA         66         86 2022-02-16
2  401364937           Vanderbilt                   Auburn        NA         2         80         94 2022-02-16
3  401364445               Purdue             Northwestern         5        NA         64         70 2022-02-16
4  401368416               Baylor               Texas Tech         7        11         73         83 2022-02-16
5  401364444             Illinois                  Rutgers        12        NA         59         70 2022-02-16
6  401373593           Seton Hall                    UConn        NA        24         65         70 2022-02-16
7  401364935    Mississippi State                  Alabama        NA        25         75         80 2022-02-16
8  401400188            Manhattan                Fairfield        NA        NA         67         74 2022-02-16
9  401381724              Colgate                     Army        NA        NA         90        100 2022-02-16
10 401370773         Presbyterian   South Carolina Upstate        NA        NA         55         60 2022-02-16
11 401373594           St. John's                   Xavier        NA        NA         73         86 2022-02-16
12 401370768             Campbell                  Radford        NA        NA         67         71 2022-02-16
13 401381748          Loyola (MD)                Lafayette        NA        NA         68         77 2022-02-16
14 401381739    Boston University               Holy Cross        NA        NA         65         78 2022-02-16
15 401373106                 Navy      American University        NA        NA         46         55 2022-02-16
16 401370771   North Carolina A&T                  Hampton        NA        NA         82         93 2022-02-16
17 401370770             Winthrop             Gardner-Webb        NA        NA         70         81 2022-02-16
18 401370769        UNC Asheville      Charleston Southern        NA        NA         66         85 2022-02-16
19 401370119                Miami               Louisville        NA        NA         63         70 2022-02-16
20 401369975       Boston College               Notre Dame        NA        NA         95         99 2022-02-16
21 401369696              Vermont            New Hampshire        NA        NA         50         71 2022-02-16
22 401369695          Stony Brook                     UMBC        NA        NA         84         95 2022-02-16
23 401369694         UMass Lowell                     NJIT        NA        NA         55         59 2022-02-16
24 401369693                Maine                 Hartford        NA        NA         65         75 2022-02-16
25 401369692               Albany               Binghamton        NA        NA         67         68 2022-02-16
26 401369309         Jacksonville                  Stetson        NA        NA         45         67 2022-02-16
27 401369307       Kennesaw State       Florida Gulf Coast        NA        NA         76         82 2022-02-16
28 401365845                UMass          St. Bonaventure        NA        NA         71         83 2022-02-16
29 401365844         George Mason           Saint Joseph's        NA        NA         70         75 2022-02-16
30 401365569               Furman         Western Carolina        NA        NA         85        103 2022-02-16
31 401365568 East Tennessee State                   Mercer        NA        NA         56         65 2022-02-16
32 401365567              Wofford              The Citadel        NA        NA         58         65 2022-02-16
33 401364936              Georgia                      LSU        NA        NA         65         84 2022-02-16
34 401408135    George Washington                 Duquesne        NA        NA         52         73 2022-02-16
35 401371525        Chicago State        Stephen F. Austin        NA        NA         71         88 2022-02-16
36 401369304        North Alabama         Eastern Kentucky        NA        NA         76         80 2022-02-16
37 401402045             La Salle              Saint Louis        NA        NA         64         90 2022-02-16
38 401373595           Georgetown                Marquette        NA        NA         66         77 2022-02-16
39 401371527          Utah Valley                 Tarleton        NA        NA         56         69 2022-02-16
40 401371526            Seattle U     UT Rio Grande Valley        NA        NA         62        102 2022-02-16
41 401369959           Pittsburgh           North Carolina        NA        NA         67         76 2022-02-16
42 401369308   Jacksonville State                 Lipscomb        NA        NA         67         78 2022-02-16
43 401369306           Bellarmine         Central Arkansas        NA        NA         69         79 2022-02-16
44 401367406       Loyola Chicago               Valparaiso        NA        NA         69         71 2022-02-16
45 401367404           Evansville                    Drake        NA        NA         51         73 2022-02-16
46 401377761                  SMU                   Temple        NA        NA         57         64 2022-02-16
47 401373250       Morehead State                UT Martin        NA        NA         60         68 2022-02-16
48 401371529          Dixie State         New Mexico State        NA        NA         64         75 2022-02-16
49 401371530         Grand Canyon       California Baptist        NA        NA         60         65 2022-02-16
50 401364781          Boise State                Air Force        NA        NA         59         85 2022-02-16
51 401364780                 UNLV             Fresno State        NA        NA         57         60 2022-02-16`

**Comment by lbenz730** [comment]
<img width="828" alt="Screen Shot 2022-02-17 at 9 46 42 AM" src="https://user-images.githubusercontent.com/21962947/154505818-9afa0acf-548f-4275-b735-86dcf50bc733.png">
