### ISSUE TITLE
get_master_schedule throwing Error

### ISSUE THREAD

**Issue by RobMepham** [lbenz730/ncaahoopR#72]
I'm getting an error using the get_master_schedule fn in recent days. I know Evan Miyakawa made a separate thread on the ESPN interface changes, but seeing as that has been resolved, and my error is persisting, I thought I'd open a new thread.

Image attached. My error is specifically seen on "2022-02-17" date.

![ERR_1](https://user-images.githubusercontent.com/78280658/154707643-d29ad409-d176-44c1-b232-2b2988e25b69.png)

My apologies if this is something on my end, but many of my stored procedures are throwing errors now since the ger_master_schedule function isn't returning as it has been.

Thanks in Advance.

**Comment by lbenz730** [comment]
Realized I forgot to push that earlier fix. Now actually pushed and fixed. Please let me know if that solves your issue!

**Comment by RobMepham** [comment]
Thanks for the timely fix. Really great stuff!
