### ISSUE TITLE
X/Y Co-ordinate Questions

### ISSUE THREAD

**Issue by silfornia** [lbenz730/ncaahoopR#74]
Hello,

Has anyone noticed the X co-ordinates have much less resolution than the Y? In addition, if you look at the histograms for the two dimensions, the maximums don't actually reach the limits of the court. For example, X-max is 47 and Y-max is 92.12 vs a 50x94 court. Any thoughts on this? Is this just the way the numbers come off the site? I guess it is impossible to take a shot from (50, 94) since you'd be stepping out of bounds when taking the shot. Maybe that's what is going on?

Thanks
-Mike

![image](https://user-images.githubusercontent.com/32369650/154827801-66100636-d7dc-447e-8cbd-aa22d661a827.png)
![image](https://user-images.githubusercontent.com/32369650/154827864-7e30b992-3f20-4cbb-ac71-b22d3f8decde.png)

**Comment by lbenz730** [comment]
This is a good question. To be honest, I have noticed some weird stuff as well. To begin with, all the 3 point attempts seem way too deep. For example, see the screen shot from ESPN for a game today between ILL-MSU. I think it's an issue w/ the numbers on the site. I'm not sure how to fix this myself...maybe I will need to manually chart a few games and see if I can apply some correction factor.


![Screen Shot 2022-02-20 at 12 14 10 AM](https://user-images.githubusercontent.com/21962947/154829404-0e1a0fd0-b044-4a2b-b5b4-b303b126313e.png)

**Comment by silfornia** [comment]
(25, 4.2) and (25, 87.9) are the most common locations for shots at the basket, so I would assume these are layups and where the hoop actually is in this co-ordinate system (as opposed to the basket being 5.25ft from the endline). To get shot distance I subtract out 25ft on the X, 4.2ft on the Y for the close end and 87.9 for the Y on the far end of the court. Then I use pythag. This seems to be a fair way to normalize and leads to 3pt shots mostly being around 22-23ft where they should be.

Thanks everyone!

Still not sure why the X-value has such low resolution though. Can anyone confirm that is exactly what is coming from ESPN?

**Comment by lbenz730** [comment]
I'm not sure about why the low x resolution. I will have to dive into the data more in the off season to perform a normalization trick. I feel as though the further back a shot is the more "off" it's Y coordinate is. For example, I think free throws are given coordinates, do those map up w/ where the free throw line is? ESPN might've switched those to the basket location itself, which could explain the massive amount of points at the basket (some combo of FT + layup or Dunk). In any case, I need to do some exploratory work on these in the offseason.
