### ISSUE TITLE
assist_net not working for 2021-22 Season

### ISSUE THREAD

**Issue by jrbarber37** [lbenz730/ncaahoopR#78]
assist_net not working for the 2021-22 Season.  works fine for 2020-21.  Also works for individual games in the 2021-22 season.  Thanks.

**Comment by lbenz730** [comment]
Thank you I will take a look

**Comment by jrbarber37** [comment]
Thank you!

**Comment by lbenz730** [comment]
Sorry for the delay but this is now fixed if you re-install package.

**Comment by jrbarber37** [comment]
Thanks so much for making this change.

John Barber
