### ISSUE TITLE
get_pbp_game not working for 2021-22 Season

### ISSUE THREAD

**Issue by jrbarber37** [lbenz730/ncaahoopR#79]
get_pbp_game not working for 2021-22 Season

code: pbp_Kansas <- get_pbp("Kansas", "2021-22")

result: Getting Game IDs: Kansas
Error in get_schedule(team) : 
  No team schedule available for Kansas / 2021-22. Current ESPN season = "2021-22". If you are trying to find the most recent season (2020-21), please  supply season = "2020-21" argument.

Thank you

**Comment by jrbarber37** [comment]
No issue with  "2020-21" argument.

**Comment by lbenz730** [comment]
I think this is fixed in issue #78 . Try a fresh re-install and let me know if issue persists

**Comment by jrbarber37** [comment]
That was my problem.  I updated ncaahoopR and everything is working for
2021-22 now.  ncaahoopR is a fantastic resource.  Thanks so much!

John
