### ISSUE TITLE
Shot location orientation and scale

### ISSUE THREAD

**Issue by j-andrews7** [lbenz730/ncaahoopR#8]
It's unclear how to interpret the shot location data, so I've got a few questions:

- What's the correct perspective? Staring down at the width of the court like a typical broadcast? 
- Where is (0, 0)? The bottom left corner of the court with the above perspective? 
- What's the scale? Feet? 

These are probably worth adding to the docs as well. Cheers.

**Comment by j-andrews7** [comment]
Tagging @meysubb as well since I know this is his contribution.

**Comment by lbenz730** [comment]
Sorry just now seeing this but I will add this information to the documents. (0,0) is the bottom left corner of the shot charts if you look at something in full court. Shot locations in the `game_shot_charts()` function are left as they are found in ESPN. When each team shots are plotted in half court, all shot locations are converted to fit within the 50 feet x 47 feet half court, with (0,0) being in the bottom left and (50,47) being in the upper right. Perspective is as if you are standing under the hoop looking towards the other hoop.

**Comment by j-andrews7** [comment]
Perfect, thanks for clarifying.

**Comment by meysubb** [comment]
Oh damn, i didn't get the notification at all. But glad y'all figure it out!
