### ISSUE TITLE
Any Lafayette game fails get_pbp_game with extra_parse=T

### ISSUE THREAD

**Issue by Cheesywizz** [lbenz730/ncaahoopR#80]
A bit of digging shows that in the `dict` dataset, both Lafayette and Lousiana have ESPN_PBP == 'Lafayette', likely the reason why a `condition has length > 1` error is raised:
```
Scraping Data for Game: 1 of 1
Error in if (is.na(team)) { : the condition has length > 1
Backtrace:
1: get_roster(dict$ESPN[which(dict$ESPN_PBP == pbp$away[1])], year)
2: get_pbp_game(401369998)
```
If I recall correctly, Louisiana used to be known as Louisiana-Lafayette and perhaps sometimes even just Lafayette for short, but recent pbp logs seem to favor just 'Louisiana'.

**Comment by lbenz730** [comment]
Thank you for bringing to my attention. I will look into this.

**Comment by lbenz730** [comment]
Seems to be working now!
