### ISSUE TITLE
Home and Away Score Swaps

### ISSUE THREAD

**Issue by letta-9** [lbenz730/ncaahoopR#82]
Great work with this package. However when using "get_master_schedule" some game scores are swapped. For example, for games on 11/7/22, master schedule says Quinnpiac lost 67-62 when they actually won. This happens with some games but not others. Either the scores are swapped or the home and away team. Thanks!

**Comment by lbenz730** [comment]
Thanks for alerting me. ESPN hemp changes from year to year. I'll look into fixing it tomorrow.

**Comment by lbenz730** [comment]
Have found the issue. Think I have a fix but doing some testing to ensure it works correctly.

**Comment by letta-9** [comment]
Great thanks!

**Comment by lbenz730** [comment]
Should be fixed now. Please take a fresh install of the lastest version and let me know if any bug persists.

**Comment by letta-9** [comment]
Looks great. Appreciate the help.

**Comment by letta-9** [comment]
After looking a little deeper, still looks like a few are incorrect after installing again. Some that were incorrect at first are now fine, however.

![Screenshot 2022-11-13 153541](https://user-images.githubusercontent.com/102425378/201543387-0988c17c-714a-4779-b3cb-68b24eb3eaf8.png)
![Screenshot 2022-11-13 1536242](https://user-images.githubusercontent.com/102425378/201543420-53f6186f-a592-42b6-8db3-b26c514aa4de.png)
![3](https://user-images.githubusercontent.com/102425378/201543668-0faadb60-1476-46dc-8102-21c8434ff1d7.png)

**Comment by lbenz730** [comment]
Ok thanks for this list. Let me see why some are still slipping through the cracks

**Comment by lbenz730** [comment]
Improved fix catches these and hopefully any others you were seeing, w/ latest install.
