### ISSUE TITLE
possession_before/possession_after columns inaccurate (2022-23 PBP data only)

### ISSUE THREAD

**Issue by professor042** [lbenz730/ncaahoopR#83]
The 2022-23 PBP dataset has many cases where the possession_before/possession_after columns are inaccurate.  I am inexperienced in R, so I generally just dump the data to a spreadsheet, but I've found that these columns don't appear to be inaccurate in ~165 games so far this season, when it was almost always accurate in previous seasons.  In many cases, the column just shows up as 'NA' while in others, only one of the two teams ever seems to be populated.  It looks like the issue is fairly evenly distributed between the different days so far this season.

Example game IDs with this issue (according to my script, ~57% of games in 2022-23, as of 11/13/22, have this problem):

- 401487328
- 401488191
- 401483281
- 401487618
- 401487470
- 401493931
- 401485026
- 401483266
- 401483320
- 401491278
- 401491839
- 401483235
- 401487711
- 401497505
- 401487636

I'm very new to R and GitHub, so I apologize if this issue has been explained or answered elsewhere.  When I looked, I couldn't find anything.

**Comment by lbenz730** [comment]
Thank you for alerting me I will take a look this week

**Comment by professor042** [comment]
May be a result of troubleshooting, but I tried to run this code this morning:

```
date <- "2022-11-16"
game_ids <- ncaahoopR::get_master_schedule(date)$game_id
ncaahoopR::get_pbp_game(game_ids, extra_parse = TRUE)
filename = paste("./pbp_files/pbp_", date, ".csv", sep = "")
write.csv(ncaahoopR::get_pbp_game(game_ids, extra_parse = TRUE), filename)
```

and got the error:

```
Error: Problem with `mutate()` column `time_remaining_half`.
i `time_remaining_half = as.character(V1)`.
x object 'V1' not found
Run `rlang::last_error()` to see where the error occurred.
```

`rlang::last_error()` **returned:**

```
> <error/dplyr:::mutate_error>
> Problem with `mutate()` column `time_remaining_half`.
> i `time_remaining_half = as.character(V1)`.
> x object 'V1' not found
> Backtrace:
>   1. utils::write.csv(...)
>  15. base::.handleSimpleError(...)
>  16. dplyr:::h(simpleError(msg, call))
> Run `rlang::last_trace()` to see the full context.
```


`rlang::last_trace()` **returned:**
```

> <error/dplyr:::mutate_error>
> Problem with `mutate()` column `time_remaining_half`.
> i `time_remaining_half = as.character(V1)`.
> x object 'V1' not found
> Backtrace:
>      x
>   1. +-utils::write.csv(...)
>   2. | \-base::eval.parent(Call)
>   3. |   \-base::eval(expr, p)
>   4. |     \-base::eval(expr, p)
>   5. +-utils::write.table(...)
>   6. | \-base::is.data.frame(x)
>   7. +-ncaahoopR::get_pbp_game(game_ids, extra_parse = TRUE)
>   8. | \-ncaahoopR:::clean(as.data.frame(tmp[[3]]), 2, 0)
>   9. |   \-`%>%`(...)
>  10. +-dplyr::mutate(...)
>  11. +-dplyr:::mutate.data.frame(...)
>  12. | \-dplyr:::mutate_cols(.data, ..., caller_env = caller_env())
>  13. |   +-base::withCallingHandlers(...)
>  14. |   \-mask$eval_all_mutate(quo)
>  15. \-base::.handleSimpleError(...)
>  16.   \-dplyr:::h(simpleError(msg, call))
> <error/simpleError>
> object 'V1' not found`
```

**Comment by lbenz730** [comment]
Thank you, I will certainly look into this. Seems related to #84

**Comment by lbenz730** [comment]
At first glance the root of this issue seems very major -- as in the whole package would have to be re-written...I'll see what I can do but I think it will take some time.

**Comment by lbenz730** [comment]
Actually I lied I think it'll be fixable.

**Comment by lbenz730** [comment]
I think I have figured out how to fix but may take a few days to get everything up and running. Thanks for alerting me and for your patience.

**Comment by professor042** [comment]
No problem. Thanks for looking into it and putting together the package in the first place.

**Comment by professor042** [comment]
Looks like an issue with the boxscores now.  I guess ESPN may have changed their site somehow or something?  Everything worked fine through games on 11/13 but now seems broken after 11/14?

**Example:**
```

> ncaahoopR::get_boxscore(401486296)
Error: Can't extract columns that don't exist.
x Column `FG` doesn't exist.
Run `rlang::last_error()` to see where the error occurred.
> rlang::last_error()
<error/vctrs_error_subscript_oob>
Can't extract columns that don't exist.
x Column `FG` doesn't exist.
Backtrace:
  1. ncaahoopR::get_boxscore(game_id)
  3. tidyr:::separate.data.frame(away, "FG", c("FGM", "FGA"), sep = "-")
  4. tidyselect::vars_pull(names(data), !!enquo(col))
  5. tidyselect:::pull_as_location2(loc, n, vars)
 13. vctrs::vec_as_location2(i, n = n, names = names, arg = "var")
 15. vctrs:::vec_as_location2_result(...)
 20. vctrs::vec_as_location(i, n, names = names, arg = arg)
 22. vctrs:::stop_subscript_oob(...)
 23. vctrs:::stop_subscript(...)
Run `rlang::last_trace()` to see the full context.
```

**Comment by lbenz730** [comment]
Yes the issue is the underlying page source changed. I will have to modify the code to parse this new format.

**Comment by lbenz730** [comment]
Have a solution that seems to be working. Some testing to come tmrw but hopefully a release by end of week

**Comment by lbenz730** [comment]
Ok all the data functions should be working again. Please let me know if any issues persist.

**Comment by professor042** [comment]
Working well this morning and yesterday.  Thanks again, this is a great resource that you've provided.
