### ISSUE TITLE
Unable to get data for most of the functions

### ISSUE THREAD

**Issue by jmichaelp62** [lbenz730/ncaahoopR#84]
Hi, I'm experiencing problems as detailed below.  This started yesterday mid-morning. There had been no restart of R, when I returned to use it after a couple of hours I couldn't pull info. Previously all worked well. I tried reinstalling the ncaahoopR package & then the entire R software, both to no avail. I tried a different school, "Florida" & also a Florida game id 401483032, but that didn't work either. Thanks.

**The following return an error**

- > get_boxscore(401483310)
Error in `tidyr::separate()`:
! Can't extract columns that don't exist.
✖ Column `FG` doesn't exist.
Run `]8;;rstudio:run:rlang::last_error()rlang::last_error()]8;;` to see where the error occurred.

- > game_flow(401483310, "blue", "gray")
Scraping Data for Game: 1 of 1
Error in if (is.nit(game_ids[g]) & get_date(game_ids[g]) <= "2022-01-01") { : 
  argument is of length zero

- > get_shot_locs(401483310)
Getting Shots for Game 1 of 1
No shot location data available for this game.
NULL

- > game_shot_chart(401483310, heatmap = F)
Getting Shots for Game 1 of 1
No shot location data available for this game.

- > wp_chart_new(401483310)
Scraping Data for Game: 1 of 1
Error in if (is.nit(game_ids[g]) & get_date(game_ids[g]) <= "2022-01-01") { : 
  argument is of length zero

- >get_pbp("Texas", "2022-23")
Getting Game IDs: Texas
Scraping Data for Game: 1 of 3
Error in if (is.nit(game_ids[g]) & get_date(game_ids[g]) <= "2022-01-01") { : 
  argument is of length zero

- > assist_net(team = "Texas", node_col = "#bf5700", season = 401483310)
Scraping Data for Game: 1 of 1
NULL
Warning message:
In assist_net(team = "Texas", node_col = "#bf5700", season = 401483310) :
  Play-by-Play Data Not Available for Assist Network

**The following work:**
 get_roster("Texas", "2022-23")
get_schedule("Texas", "2022-23")
get_game_ids("Texas", "2022-23")

**Comment by lbenz730** [comment]
Thank you, I will certainly look into this.

**Comment by lbenz730** [comment]
At first glance the root of this issue seems very major -- as in the whole package would have to be re-written...I'll see what I can do but I think it will take some time.

**Comment by lbenz730** [comment]
c

**Comment by lbenz730** [comment]
I think I have figured out how to fix but may take a few days to get everything up and running. Thanks for alerting me and for your patience.

**Comment by jmichaelp62** [comment]
Thanks so much for looking into this & figuring out a solution.

**Comment by lbenz730** [comment]
Have a solution that seems to be working. Some testing to come tmrw but hopefully a release by end of week

**Comment by jmichaelp62** [comment]
Thanks! I wish I knew how to help.

**Comment by mtkearney** [comment]
Luke, thanks so much for the fix, it's working great! Slight improvement - FGA/FGM are coming through as characters, not doubles. I fixed using sapply, but just wanted to let you know in case it's something easy to fix on your end

**Comment by lbenz730** [comment]
Fixed this so should come through as doubles now like the rest of them, if you re-install.
