### ISSUE TITLE
Score Column Error

### ISSUE THREAD

**Issue by silfornia** [lbenz730/ncaahoopR#86]
Running these two commands and I'm getting errors pulling pbp data. Just installed R, devtools and hoopR.

> pbp_games <- get_master_schedule('2022-11-09')
> pbp_data <- get_pbp_game(pbp_games[,1])

<img width="603" alt="image" src="https://user-images.githubusercontent.com/32369650/207228081-c5c3280e-2a3d-452b-a87a-945ad6133309.png">

Running R 4.1.0

Any thoughts?

Thanks,
Mike

**Comment by lbenz730** [comment]
Looks like no PBP exists for that game (https://www.espn.com/mens-college-basketball/game/_/gameId/401494479)

I pushed a fix to better handle when no Play-by-Play exist. Just re-install package and give it a whirl.
