### ISSUE TITLE
Condition Length Error

### ISSUE THREAD

**Issue by silfornia** [lbenz730/ncaahoopR#87]
Thank you for supporting this package Luke as we work through the errors. I suspect they are mostly due to the new format

Executing these commands gives the following error when scraping game 112 out of 200

<img width="298" alt="image" src="https://user-images.githubusercontent.com/32369650/207997835-7b3f7b07-91ef-41c9-ad41-6a4599f90da7.png">

<img width="404" alt="image" src="https://user-images.githubusercontent.com/32369650/207998086-7adf861c-8cbc-42f1-bf43-1107831583b1.png">

Thanks for looking into this!
-Mike

**Comment by lbenz730** [comment]
Thanks for alerting me. Will look into it and fix this week. Thank you for your patience w/ the new format of ESPN. Scraping is working for most games but clearly there are a few new edge cases I need to fix. I'll shoot a note once its fixed. 
--Luke

**Comment by lbenz730** [comment]
Related to #80 which are now both patched.

**Comment by silfornia** [comment]
Hi Luke,

Still getting this error on game 112 on 11-7-22 when I pull PBP and I believe I've updated correctly.

<img width="1232" alt="image" src="https://user-images.githubusercontent.com/32369650/208819227-eadee023-88f5-4244-a683-4091bd119246.png">

I am getting these errors when I force install. Could these be the real problem?

<img width="1168" alt="image" src="https://user-images.githubusercontent.com/32369650/208819406-469f9253-9976-4885-a054-9d762ef2e533.png">

Thanks!
Mike

**Comment by lbenz730** [comment]
Embarrassingly I fixed it locally and had forgotten to push. Try a pull now (shouldn't need to force install now that push has been made)

**Comment by silfornia** [comment]
Works! Thanks Luke!!!
