### ISSUE TITLE
IsFour Error

### ISSUE THREAD

**Issue by silfornia** [lbenz730/ncaahoopR#88]
Another one...

<img width="314" alt="image" src="https://user-images.githubusercontent.com/32369650/209022233-9f4e8e82-8239-49a8-a6c5-0e24447c3d62.png">

Gives the following error:

<img width="610" alt="image" src="https://user-images.githubusercontent.com/32369650/209022404-707aa3d3-b92c-4866-bdf5-53fc9c862109.png">

Again, thanks to Luke for working through these.

-Mike

**Comment by lbenz730** [comment]
Fixed this one. Very helpful what you are doing. Keep em' coming!

**Comment by silfornia** [comment]
Works! Thanks again!
