### ISSUE TITLE
Schedule Pull On Days w/ No Games

### ISSUE THREAD

**Issue by silfornia** [lbenz730/ncaahoopR#89]
Looks like there are subscript out of range errors on days with no games when a schedule pull is invoked. Probably just needs a throw when that occurs. Thanks!

<img width="289" alt="image" src="https://user-images.githubusercontent.com/32369650/210696650-7e1b0d4f-f79e-40e3-92a6-21b142e8c741.png">

**Comment by jrbarber37** [comment]
I am experiencing this same error on game day._

**Comment by lbenz730** [comment]
Thanks for the heads up. Just pushed a fix that should resolve this.
