### ISSUE TITLE
Improvement - Player IDs to get_roster()

### ISSUE THREAD

**Issue by mtkearney** [lbenz730/ncaahoopR#90]
Not sure if this is possible, but it would be awesome to get the player_id field from get_boxscore() in the get_roster() function - trying to join the player years to their statistics. thanks in advance!

**Comment by lbenz730** [comment]
Great idea. Think this should be doable. Let me take a look

**Comment by lbenz730** [comment]
Ok `player_id` column is now available in rosters. Just update to latest version of the package.

**Comment by mtkearney** [comment]
You're awesome - thanks so much!
