### ISSUE TITLE
Issue: get_boxscore() not functioning / "lazy-load db is corrupt"

### ISSUE THREAD

**Issue by mtkearney** [lbenz730/ncaahoopR#91]
Attached screenshots of both issues. Corrupt issue only came up when trying to load info about a function. get_boxscore / season_boxscore do not work for any team.

Seemed to start after last night's update. Have tried multiple installs.
<img width="295" alt="Screen Shot 2023-01-12 at 11 02 20 AM" src="https://user-images.githubusercontent.com/72845288/212145812-6fb627dc-6f1e-42a7-bdd8-16e5e3d94a38.png">
<img width="1046" alt="Screen Shot 2023-01-12 at 11 02 42 AM" src="https://user-images.githubusercontent.com/72845288/212145818-9af42349-fdd2-4548-978c-6c31d9b0fa55.png">

**Comment by lbenz730** [comment]
I've run into this problem before. Usually happens if you install w/out restarting R completely first. Give that a try

**Comment by lbenz730** [comment]
Does now seem to be a seperate issue in get_boxscore -- working on that now

**Comment by lbenz730** [comment]
Pushed a fix. Also game sure season_boxscore had player_ids for you. Install latest version (after restarting R) and everything should work ok

**Comment by mtkearney** [comment]
my bad on the restart, that side works fine now. boxscore functionality still seems to throw me the same error, even after multiple restarts/reinstalls. get_pbp works though. if it's working for you, I'll give it some time and try again. really do appreciate all the help.

**Comment by lbenz730** [comment]
That's my bad i made he changes but didn't actually push. Try now
<img width="1087" alt="Screen Shot 2023-01-12 at 3 31 30 PM" src="https://user-images.githubusercontent.com/21962947/212174861-b80f61af-b040-4cf3-8931-ba5ceb4afc7c.png">

**Comment by mtkearney** [comment]
works perfectly! thank you so much!
