### ISSUE TITLE
Season Box Score issues

### ISSUE THREAD

**Issue by ccaudill11** [lbenz730/ncaahoopR#94]
box <- season_boxscore(team= "Kentucky", season = "2022-23", aggregate = "total")
Pulling Box Score Data for Game: 1 of 20
Pulling Box Score Data for Game: 2 of 20
Pulling Box Score Data for Game: 3 of 20
Pulling Box Score Data for Game: 4 of 20
Pulling Box Score Data for Game: 5 of 20
Pulling Box Score Data for Game: 6 of 20
Pulling Box Score Data for Game: 7 of 20
Pulling Box Score Data for Game: 8 of 20
Pulling Box Score Data for Game: 9 of 20
Pulling Box Score Data for Game: 10 of 20
Pulling Box Score Data for Game: 11 of 20
Pulling Box Score Data for Game: 12 of 20
Pulling Box Score Data for Game: 13 of 20
Pulling Box Score Data for Game: 14 of 20
Pulling Box Score Data for Game: 15 of 20
Pulling Box Score Data for Game: 16 of 20
Pulling Box Score Data for Game: 17 of 20
Pulling Box Score Data for Game: 18 of 20
Pulling Box Score Data for Game: 19 of 20
Pulling Box Score Data for Game: 20 of 20
**Error:
! Column name `player` must not be duplicated.
Use .name_repair to specify repair.
Caused by error in `repaired_names()`:
! Names must be unique.
✖ These names are duplicated:
  * "player" at locations 2 and 3.
Run `rlang::last_error()` to see where the error occurred.**

I am trying to run this code and get this error message. I tried deleting and reinstalling the package but no luck. Any ideas?

**Comment by lbenz730** [comment]
Try to re-install now. Just pushed a bug fix for this issue.
