### ISSUE TITLE
Bug in get_master_schedule()

### ISSUE THREAD

**Issue by danmalter** [lbenz730/ncaahoopR#97]
There is an error in your get_master_schedule() function that can be reproduced by running get_master_schedule("2022-11-11").

On 2022-11-11 there were 83 completed games and 1 game that was postponed.

In the below line, since you're removing n_postponed (value of 1) you're only assigning 82 game_ids instead of 83 game_ids.

`x <- x[1:(n_scheduled + n_completed - n_canceled - n_postponed)]
`

as a result, when you run:

`schedule <- dplyr::mutate(schedule, "game_id" = x[1:nrow(schedule)])
`

The 83rd game gets a game_id of NA because the length of x is 82.

**Comment by lbenz730** [comment]
Thanks I'll take a look into this.

**Comment by rossdrucker** [comment]
Took a look through this, and it looks to me like only 81 events are read in via:

```r
z <- XML::readHTMLTable(RCurl::getURL(url))
```

Agreed with @danmalter that the line that causes the game to not receive a `game_id` is

```r
schedule <- dplyr::mutate(schedule, "game_id" = x[1:nrow(schedule)])
```

but not sure why it's not reading in all 84 games that were initially scheduled? Confirmed with

```r
hoopR::espn_mbb_scoreboard("20221111")
```

and there's 84 games that are coming through, and on [the schedule page for that day](https://www.espn.com/mens-college-basketball/schedule/_/date/20221111) there are 84 games.

In looking at it a bit deeper, there's a game from the prior day (Alabama State @ USC), and it seems to put other games from 11/11/22 towards 11/12/22 (e.g. Long Beach State @ UCLA, UC Irvine @ Oregon, and others). Not sure why this is happening

**Comment by lbenz730** [comment]
This is working again
